version: '3.2'
services:
  database:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: 'test'
      MYSQL_ROOT_PASSWORD: '1234'
    ports:
      - "3306:3306"
    expose:
      - '3306'
  app:
    build: ./node
    ports:
      - "3000:3000" 